#!/system/bin/sh
# ============================================================
# autostart-network.sh
# Auto-enable mobile data + Wi-Fi hotspot right after boot,
# on rooted Android (Magisk service.d).
#
# Credentials now live in hotspot-config.sh (same folder),
# generated by install.sh. Run install.sh again any time you
# want to change SSID/password/security — no nano needed.
# ============================================================

DIR="$(dirname "$0")"
CONFIG="$DIR/hotspot-config.sh"
LOG=/data/local/tmp/autostart-network.log
RETRY_LIMIT=30   # 30 * 2s = 60s max wait per service

if [ ! -f "$CONFIG" ]; then
    echo "$(date): hotspot-config.sh not found next to this script. Run install.sh again." > "$LOG"
    exit 1
fi
# shellcheck source=/dev/null
. "$CONFIG"

wait_for_service() {
    # $1 = service name (e.g. "phone", "wifi")
    svc_name="$1"
    i=0
    while ! /system/bin/service check "$svc_name" | grep -q found; do
        sleep 2
        i=$((i + 1))
        if [ "$i" -ge "$RETRY_LIMIT" ]; then
            echo "   WARNING: '$svc_name' service not confirmed after $((RETRY_LIMIT * 2))s — proceeding anyway"
            return 1
        fi
    done
    return 0
}

{
    echo "1. start: $(date)"

    while [ "$(getprop sys.boot_completed)" != "1" ]; do
        sleep 2
    done
    echo "2. boot_completed: $(date)"

    wait_for_service phone
    echo "3. phone service: $(/system/bin/service check phone) - $(date)"

    /system/bin/svc data enable
    echo "4. mobile data enabled: $(date)"

    wait_for_service wifi
    echo "5. wifi service: $(/system/bin/service check wifi) - $(date)"

    sleep 5
    /system/bin/cmd wifi start-softap "$SSID" "$SECURITY" "$PASSWORD"
    echo "6. hotspot command sent: $(date)"

} > "$LOG" 2>&1
